### ISSUE TITLE
[Feature]: Update docs

### ISSUE THREAD

**Issue by ilyaZar** [Appsilon/tapyr-template#43]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Description

Hi @pstorozenko great work here !

I wonder whether it is possible to update the docs and:

1. add a section on using `auth0` or other ways for login in this framework
2. how the best practice is to restrict the user to a specific version of a shiny app (so e.g. some tabs in a shiny app can be seen by a user and some can not depending on the user permission settings; permission settings could be retrieved from within the app via the login-data passed via `auth0`, so the app knows which user is logged in, and can display tabs of the app depending on the permission setup for this user)

and actually point to the documentation files. When reading the tapyr-docs webpage https://connect.appsilon.com/tapyr-docs/ I could not find the raw files (I found some typos and it would be great if users of `tapyr` could simply PR changes to the docs).

Kind regards and thanks again for making this template, it is very useful !

### Problem

Can't find docs

### Proposed Solution

Point to docs, update with `auth0` info and/or other ways how login can be confiugred.

### Alternatives Considered

None. I am familiar with R Shiny, no idea how this is done in PyShiny

**Comment by pstorozenko** [comment]
Hey @ilyaZar 
thanks for your idea, the authentication is indeed an important part of production-grade apps!

As Appsilon, we're Posit partners and we promote and believe that deploying apps on Posit Connect is the best for Enterprise cases if you take into account all factors.
This is the core of our work.
Posit Connect provides the authentication mechanisms and it's against the license to create custom mechanisms if you deploy there.
This is why it's not covered in the docs :)

That being said, if one would like to deploy and secure app with login-password, I'd dig in there:
1. When you deploy app on GCP Cloud Run/App Engine you can secure the app with IAP, then you have the authentication outside of the app completely. With AWS, you can use AWS Cognito.
2. Remember that `shiny` is based on `starlette`, as many other libraries. Maybe on of the links
  1. How `shiny` apps are just endpoints in the `starlette` application https://www.appsilon.com/post/shiny-for-python-routing
  2. Oauth authentication for `starlette` applications https://docs.authlib.org/en/latest/client/starlette.html
  3. https://github.com/gradio-app/gradio/issues/7005
  4. https://github.com/gradio-app/gradio/issues/2790
will help you get inspiration on how to implement the authentication.

I'll double check if we can open the docs and write there about authentication with other folks at Appsilon.

I hope the links will help you, thanks for the insights!
