### ISSUE TITLE
[Bug]: Link to getting started blog post is broken

### ISSUE THREAD

**Issue by mtworth** [Appsilon/tapyr-template#55]
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### What happened?

The link to the "getting started" blog post on the README is broken: 
https://github.com/Appsilon/tapyr-template/blob/main/www.appsilon.com/post/introducing-tapyr

### Steps to reproduce

1.Click on link
2.
3.
...

### Expected behavior

Navigate to blogpost

**Comment by pstorozenko** [comment]
Thanks a lot for spotting this!
Closed by #56
